# -*- mode: sh -*-

alias vi=vim

export PS1='[\[\033[01;32m\]\u\[\033[00m\]@\[\033[01;36m\]\h\[\033[00m\] \[\033[01;34m\]\w\[\033[00m\]] $(ec=$?;[ $ec -ne 0 ] && echo "\[\033[01;31m\]$ec\[\033[00m\] ")\$ '
export EDITOR=vim
